name: Infrastructure Deployment Pipeline

on:
  push:
    branches:
      - staging
    paths:
      - 'ECS-cdk/**'  # Only trigger this job if files in the infra directory change

jobs:
  deploy_infrastructure:
    runs-on: ubuntu-latest

    steps:
      # Checkout only the infra directory to optimize speed
      - name: Checkout Infra Directory
        uses: actions/checkout@v2
        with:
          path: infra  # Check out only the infra directory

      # Install AWS CDK
      - name: Install AWS CDK
        run: |
          npm install -g aws-cdk

      # Deploy CDK Stack
      - name: Deploy CDK Stack
        working-directory: infra  # Run CDK deploy from the infra directory
        run: |
          cd ECS-cdk
          cdk deploy --require-approval never