name: Infrastructure Deployment Pipeline

on:
  push:
    branches:
      - staging
    paths:
      - 'earnipay-cdk/**'

jobs:
  deploy_infrastructure:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Infra Directory
        uses: actions/checkout@v2

      # Set up AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install dependencies for CDK (specifically for Python CDK)
      - name: Install CDK Python Dependencies
        run: |
          cd earnipay-cdk
          pip install -r requirements.txt

      # Install AWS CDK CLI (global tool)
      - name: Install AWS CDK CLI
        run: npm install -g aws-cdk

      # Deploy CDK Stack
      - name: Deploy CDK EarnipayCdkStack
        working-directory: earnipay-cdk
        run: |
          cdk deploy --require-approval never