name: Infrastructure Deployment Pipeline

on:
  push:
    branches:
      - staging
    paths:
      - 'ECS-cdk/**'  # Only trigger this job if files in the ECS-cdk directory change

jobs:
  deploy_infrastructure:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Infra Directory
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install dependencies for CDK (specifically for Python CDK)
      - name: Install CDK Python Dependencies
        run: |
          cd /Users/muhammadyekini/Downloads/Data-infrastructure/my_insights/ECS-cdk
          pip install -r requirements.txt

      # Install AWS CDK CLI (global tool)
      - name: Install AWS CDK CLI
        run: npm install -g aws-cdk

      # Deploy CDK Stack
      - name: Deploy CDK Stack
        working-directory: my_insights/ECS-cdk  # Adjust working directory path
        run: |
          cdk deploy --require-approval never