name: CI/CD Pipeline for Frappe Insights

on:
  push:
    branches:
      - staging

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: 816069156617
  ECR_REPOSITORY: earnipay/dashboard
  ECS_CLUSTER: earnipay-cluster
  ECS_SERVICE: earnipay-service

jobs:
  build_and_deploy_application:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl
          curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version
        timeout-minutes: 5

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Build only the frappe image
      - name: Build Frappe Docker Image
        id: build_images
        run: |
          cd docker
          docker-compose build frappe

      # Login to Amazon ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

      # Tag and Push Frappe Docker Image
      - name: Tag and Push Frappe Docker Image
        id: tag_and_push_images
        run: |
          docker tag frappe/bench:latest ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:frappe-staging-latest
          docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:frappe-staging-latest

    outputs:
      FRAPPE_TAG: frappe-staging-latest